source_folder: gx/sample_data/customers
asset_name: sample_customers_2020
batch_definition_name: customers_2020.csv
batch_definition_path: customers_2020.csv
expectation_suite_name: adls_data_quality_suite
definition_name: adls_checkpoint
