ds_sample_data:
  source_folder: gx/sample_data/customers
  asset_name: sample_customers_2019
  batch_definition_name: customers_2019.csv
  batch_definition_path: customers_2019.csv
  expectation_suite_name: adls_data_quality_suite
  definition_name: adls_checkpoint

ds_sample_data_2019:
  source_folder: gx/sample_data/customers
  asset_name: sample_customers_2019
  batch_definition_name: customers_2019.csv
  batch_definition_path: customers_2019.csv
  expectation_suite_name: adls_data_quality_suite
  definition_name: adls_checkpoint

ds_sample_data_2020:
  source_folder: gx/sample_data/customers
  asset_name: sample_customers_2020
  batch_definition_name: customers_2020.csv
  batch_definition_path: customers_2020.csv
  expectation_suite_name: adls_data_quality_suite
  definition_name: adls_checkpoint

# Example other data source (commented):
# ds_other:
#   source_folder: dq_great_expectations/other_data/folder
#   asset_name: other_asset
#   batch_definition_name: file.parquet
#   batch_definition_path: file.parquet
#   expectation_suite_name: other_suite
#   definition_name: other_checkpoint
